import { CategoryData } from './types';

/**
 * Banco de datos masivo para "El Impostor Pro Ultra"
 * Contiene 21 categorías con 35 elementos cada una (735 palabras en total).
 * Todas las pistas son de una sola palabra.
 * Localizado para España.
 */
export const CATEGORIES_DATA: Record<string, CategoryData[]> = {
    "Objetos Cotidianos": [
        { civ: "Móvil", imp: "Tablet", hint: "Dispositivo" },
        { civ: "Llaves", imp: "Mando", hint: "Apertura" },
        { civ: "Reloj", imp: "Cronómetro", hint: "Tiempo" },
        { civ: "Gafas", imp: "Lentillas", hint: "Visión" },
        { civ: "Bolígrafo", imp: "Rotulador", hint: "Escritura" },
        { civ: "Fregona", imp: "Escoba", hint: "Limpieza" },
        { civ: "Paraguas", imp: "Chubasquero", hint: "Protección" },
        { civ: "Cuchara", imp: "Tenedor", hint: "Cubierto" },
        { civ: "Silla", imp: "Taburete", hint: "Asiento" },
        { civ: "Cama", imp: "Sofá", hint: "Mueble" },
        { civ: "Espejo", imp: "Cristal", hint: "Reflejo" },
        { civ: "Libro", imp: "Revista", hint: "Lectura" },
        { civ: "Monedero", imp: "Cartera", hint: "Dinero" },
        { civ: "Zapatillas", imp: "Zapatos", hint: "Calzado" },
        { civ: "Peine", imp: "Cepillo", hint: "Cabello" },
        { civ: "Vela", imp: "Bombilla", hint: "Iluminación" },
        { civ: "Mochila", imp: "Maleta", hint: "Equipaje" },
        { civ: "Toalla", imp: "Albornoz", hint: "Aseo" },
        { civ: "Televisor", imp: "Monitor", hint: "Pantalla" },
        { civ: "Botella", imp: "Cantimplora", hint: "Recipiente" },
        { civ: "Ventilador", imp: "Climatizador", hint: "Aire" },
        { civ: "Tijeras", imp: "Cúter", hint: "Corte" },
        { civ: "Cargador", imp: "Batería", hint: "Energía" },
        { civ: "Almohada", imp: "Cojín", hint: "Descanso" },
        { civ: "Plato", imp: "Cuenco", hint: "Vajilla" },
        { civ: "Caja", imp: "Paquete", hint: "Almacenaje" },
        { civ: "Papel", imp: "Cartón", hint: "Material" },
        { civ: "Auriculares", imp: "Altavoz", hint: "Audio" },
        { civ: "Plancha", imp: "Secador", hint: "Electrodoméstico" },
        { civ: "Martillo", imp: "Alicates", hint: "Herramienta" },
        { civ: "Cinturón", imp: "Tirantes", hint: "Ropa" },
        { civ: "Agenda", imp: "Calendario", hint: "Organización" },
        { civ: "Cafetera", imp: "Tetera", hint: "Cocina" },
        { civ: "Papelera", imp: "Contenedor", hint: "Basura" },
        { civ: "Sombrero", imp: "Gorra", hint: "Cabeza" }
    ],
    "Personas Famosas": [
        { civ: "Rosalía", imp: "Aitana", hint: "Cantante" },
        { civ: "Rafa Nadal", imp: "Carlos Alcaraz", hint: "Tenista" },
        { civ: "Ibai Llanos", imp: "AuronPlay", hint: "Streamer" },
        { civ: "Antonio Banderas", imp: "Javier Bardem", hint: "Actor" },
        { civ: "Penélope Cruz", imp: "Blanca Suárez", hint: "Actriz" },
        { civ: "Fernando Alonso", imp: "Carlos Sainz", hint: "Piloto" },
        { civ: "Pau Gasol", imp: "Marc Gasol", hint: "Baloncesto" },
        { civ: "Dalí", imp: "Picasso", hint: "Artista" },
        { civ: "Cervantes", imp: "Quevedo", hint: "Escritor" },
        { civ: "Iniesta", imp: "Casillas", hint: "Futbolista" },
        { civ: "Leo Messi", imp: "Cristiano", hint: "Delantero" },
        { civ: "Elon Musk", imp: "Bill Gates", hint: "Empresario" },
        { civ: "Almodóvar", imp: "Amenábar", hint: "Director" },
        { civ: "Alaska", imp: "Chenoa", hint: "Música" },
        { civ: "Joaquín Sabina", imp: "Serrat", hint: "Cantautor" },
        { civ: "Rubius", imp: "Grefg", hint: "Influencer" },
        { civ: "De Gea", imp: "Oblak", hint: "Portero" },
        { civ: "Úrsula Corberó", imp: "Najwa Nimri", hint: "Interpretación" },
        { civ: "Felipe VI", imp: "Letizia", hint: "Realeza" },
        { civ: "Belén Esteban", imp: "Jorge Javier", hint: "Televisión" },
        { civ: "Lady Gaga", imp: "Madonna", hint: "Pop" },
        { civ: "Don Quijote", imp: "Sancho Panza", hint: "Literatura" },
        { civ: "Yamal", imp: "Williams", hint: "Selección" },
        { civ: "Santiago Segura", imp: "Dani Rovira", hint: "Cine" },
        { civ: "LeBron James", imp: "Curry", hint: "NBA" },
        { civ: "Shakira", imp: "Karol G", hint: "Latina" },
        { civ: "Bad Bunny", imp: "Quevedo", hint: "Urbano" },
        { civ: "Taylor Swift", imp: "Beyoncé", hint: "Estrella" },
        { civ: "Mbappé", imp: "Haaland", hint: "Goleador" },
        { civ: "Broncano", imp: "Buenafuente", hint: "Humor" },
        { civ: "Paco de Lucía", imp: "Camarón", hint: "Flamenco" },
        { civ: "Amancio Ortega", imp: "Juan Roig", hint: "Negocios" },
        { civ: "Lola Flores", imp: "Rocío Jurado", hint: "Folclore" },
        { civ: "Risto Mejide", imp: "Arturo Valls", hint: "Presentador" },
        { civ: "Bizarrap", imp: "Guetta", hint: "Productor" }
    ],
    "Comidas y Bebidas": [
        { civ: "Tortilla", imp: "Revuelto", hint: "Huevo" },
        { civ: "Gazpacho", imp: "Salmorejo", hint: "Tomate" },
        { civ: "Paella", imp: "Risotto", hint: "Arroz" },
        { civ: "Croqueta", imp: "Empanadilla", hint: "Frito" },
        { civ: "Jamón", imp: "Lomo", hint: "Embutido" },
        { civ: "Cerveza", imp: "Sidra", hint: "Alcohol" },
        { civ: "Café", imp: "Cortado", hint: "Cafeína" },
        { civ: "Vino", imp: "Cava", hint: "Bebida" },
        { civ: "Zumo", imp: "Batido", hint: "Fruta" },
        { civ: "Churros", imp: "Porras", hint: "Masa" },
        { civ: "Pizza", imp: "Lasaña", hint: "Pasta" },
        { civ: "Sushi", imp: "Sashimi", hint: "Pescado" },
        { civ: "Hamburguesa", imp: "Perrito", hint: "Carne" },
        { civ: "Bravas", imp: "Alioli", hint: "Patatas" },
        { civ: "Agua", imp: "Casera", hint: "Líquido" },
        { civ: "Cola", imp: "Fanta", hint: "Refresco" },
        { civ: "Taco", imp: "Burrito", hint: "México" },
        { civ: "Helado", imp: "Sorbeto", hint: "Frío" },
        { civ: "Lentejas", imp: "Garbanzos", hint: "Legumbre" },
        { civ: "Bacalao", imp: "Merluza", hint: "Mar" },
        { civ: "Manchego", imp: "Cabrales", hint: "Queso" },
        { civ: "Calamares", imp: "Chopitos", hint: "Molusco" },
        { civ: "Donut", imp: "Croissant", hint: "Bollería" },
        { civ: "Albóndigas", imp: "Filete", hint: "Carne" },
        { civ: "Leche", imp: "Horchata", hint: "Blanco" },
        { civ: "Té", imp: "Poleo", hint: "Infusión" },
        { civ: "Pipas", imp: "Almendras", hint: "Fruto" },
        { civ: "Macarrones", imp: "Tallarines", hint: "Trigo" },
        { civ: "Yogur", imp: "Cuajada", hint: "Lácteo" },
        { civ: "Mojito", imp: "Daiquiri", hint: "Cóctel" },
        { civ: "Flan", imp: "Natillas", hint: "Postre" },
        { civ: "Chistorra", imp: "Chorizo", hint: "Cerdo" },
        { civ: "Pan", imp: "Baguette", hint: "Harina" },
        { civ: "Aceitunas", imp: "Pepinillos", hint: "Aperitivo" },
        { civ: "Whisky", imp: "Ron", hint: "Destilado" }
    ],
    "Animales": [
        { civ: "Perro", imp: "Lobo", hint: "Cánido" },
        { civ: "Gato", imp: "Lince", hint: "Felino" },
        { civ: "Caballo", imp: "Burro", hint: "Equino" },
        { civ: "Vaca", imp: "Toro", hint: "Ganado" },
        { civ: "Águila", imp: "Halcón", hint: "Rapaz" },
        { civ: "León", imp: "Tigre", hint: "Fiera" },
        { civ: "Elefante", imp: "Mamut", hint: "Trompa" },
        { civ: "Delfín", imp: "Orca", hint: "Mamífero" },
        { civ: "Serpiente", imp: "Víbora", hint: "Reptil" },
        { civ: "Mono", imp: "Gorila", hint: "Primate" },
        { civ: "Oveja", imp: "Cabra", hint: "Granja" },
        { civ: "Gallina", imp: "Pato", hint: "Ave" },
        { civ: "Tiburón", imp: "Raya", hint: "Marino" },
        { civ: "Hormiga", imp: "Abeja", hint: "Insecto" },
        { civ: "Oso", imp: "Panda", hint: "Plantígrado" },
        { civ: "Conejo", imp: "Liebre", hint: "Orejas" },
        { civ: "Rana", imp: "Sapo", hint: "Anfibio" },
        { civ: "Pingüino", imp: "Foca", hint: "Antártida" },
        { civ: "Jirafa", imp: "Cebra", hint: "Sabana" },
        { civ: "Cerdo", imp: "Jabalí", hint: "Suido" },
        { civ: "Mariposa", imp: "Polilla", hint: "Volador" },
        { civ: "Araña", imp: "Alacrán", hint: "Arácnido" },
        { civ: "Murciélago", imp: "Vampiro", hint: "Nocturno" },
        { civ: "Canguro", imp: "Koala", hint: "Australia" },
        { civ: "Camello", imp: "Dromedario", hint: "Desierto" },
        { civ: "Pulpo", imp: "Sepia", hint: "Cefalópodo" },
        { civ: "Búho", imp: "Lechuza", hint: "Noche" },
        { civ: "Ardilla", imp: "Hamster", hint: "Roedor" },
        { civ: "Loro", imp: "Periquito", hint: "Pájaro" },
        { civ: "Cocodrilo", imp: "Iguana", hint: "Escamas" },
        { civ: "Caracol", imp: "Babosa", hint: "Molusco" },
        { civ: "Zorro", imp: "Hiena", hint: "Astuto" },
        { civ: "Flamenco", imp: "Cigüeña", hint: "Zancuda" },
        { civ: "Hipopótamo", imp: "Rinoceronte", hint: "Pesado" },
        { civ: "Medusa", imp: "Coral", hint: "Invertebrado" }
    ],
    "Marcas y Logotipos": [
        { civ: "Zara", imp: "Mango", hint: "Moda" },
        { civ: "Mercadona", imp: "Lidl", hint: "Supermercado" },
        { civ: "Nike", imp: "Puma", hint: "Deporte" },
        { civ: "Apple", imp: "Samsung", hint: "Tecnología" },
        { civ: "Coca-Cola", imp: "Pepsi", hint: "Refresco" },
        { civ: "Seat", imp: "Renault", hint: "Coche" },
        { civ: "Iberia", imp: "Vueling", hint: "Vuelo" },
        { civ: "Santander", imp: "BBVA", hint: "Banco" },
        { civ: "Movistar", imp: "Vodafone", hint: "Móvil" },
        { civ: "Repsol", imp: "Cepsa", hint: "Energía" },
        { civ: "Amazon", imp: "AliExpress", hint: "Compra" },
        { civ: "Netflix", imp: "HBO", hint: "Contenido" },
        { civ: "Instagram", imp: "Facebook", hint: "Social" },
        { civ: "Starbucks", imp: "Dunkin", hint: "Café" },
        { civ: "McDonald's", imp: "Burger", hint: "Comida" },
        { civ: "Nivea", imp: "Dove", hint: "Cuidado" },
        { civ: "Lego", imp: "Playmobil", hint: "Juguete" },
        { civ: "Danone", imp: "Nestlé", hint: "Alimento" },
        { civ: "El Corte Inglés", imp: "Fnac", hint: "Tienda" },
        { civ: "IKEA", imp: "Leroy", hint: "Hogar" },
        { civ: "Disney", imp: "Pixar", hint: "Dibujos" },
        { civ: "Spotify", imp: "Tidal", hint: "Música" },
        { civ: "PlayStation", imp: "Xbox", hint: "Consola" },
        { civ: "Ferrari", imp: "Porsche", hint: "Lujo" },
        { civ: "Lacoste", imp: "Ralph", hint: "Prestigio" },
        { civ: "Hacendado", imp: "Carrefour", hint: "Blanca" },
        { civ: "Campofrío", imp: "ElPozo", hint: "Cárnica" },
        { civ: "Bimbo", imp: "Panrico", hint: "Pan" },
        { civ: "Telepizza", imp: "Domino's", hint: "Pizza" },
        { civ: "Visa", imp: "Mastercard", hint: "Tarjeta" },
        { civ: "Google", imp: "Yahoo", hint: "Buscador" },
        { civ: "Rolex", imp: "Casio", hint: "Reloj" },
        { civ: "Red Bull", imp: "Monster", hint: "Bebida" },
        { civ: "Renfe", imp: "Iryo", hint: "Tren" },
        { civ: "Bershka", imp: "Stradivarius", hint: "Inditex" }
    ],
    "Colores y Formas": [
        { civ: "Rojo", imp: "Granate", hint: "Cálido" },
        { civ: "Azul", imp: "Cian", hint: "Frío" },
        { civ: "Círculo", imp: "Óvalo", hint: "Curva" },
        { civ: "Cuadrado", imp: "Rectángulo", hint: "Ángulo" },
        { civ: "Amarillo", imp: "Dorado", hint: "Brillante" },
        { civ: "Verde", imp: "Lima", hint: "Natural" },
        { civ: "Triángulo", imp: "Rombo", hint: "Geometría" },
        { civ: "Rosa", imp: "Fucsia", hint: "Color" },
        { civ: "Negro", imp: "Gris", hint: "Oscuro" },
        { civ: "Blanco", imp: "Beige", hint: "Claro" },
        { civ: "Naranja", imp: "Butano", hint: "Fruta" },
        { civ: "Morado", imp: "Lila", hint: "Violeta" },
        { civ: "Cubo", imp: "Esfera", hint: "Volumen" },
        { civ: "Estrella", imp: "Pentágono", hint: "Puntas" },
        { civ: "Hexágono", imp: "Octógono", hint: "Lados" },
        { civ: "Marrón", imp: "Castaño", hint: "Tierra" },
        { civ: "Transparente", imp: "Opaco", hint: "Efecto" },
        { civ: "Mate", imp: "Brillo", hint: "Acabado" },
        { civ: "Línea", imp: "Punto", hint: "Trazo" },
        { civ: "Diamante", imp: "Pica", hint: "Baraja" },
        { civ: "Turquesa", imp: "Esmeralda", hint: "Piedra" },
        { civ: "Plata", imp: "Bronce", hint: "Metal" },
        { civ: "Corazón", imp: "Cruz", hint: "Símbolo" },
        { civ: "Flecha", imp: "Rayo", hint: "Icono" },
        { civ: "Cilindro", imp: "Cono", hint: "Cuerpo" },
        { civ: "Espiral", imp: "Zigzag", hint: "Dibujo" },
        { civ: "Neón", imp: "Flúor", hint: "Llamativo" },
        { civ: "Cápsula", imp: "Pastilla", hint: "Farmacia" },
        { civ: "Mancha", imp: "Gota", hint: "Líquido" },
        { civ: "Sombra", imp: "Luz", hint: "Visión" },
        { civ: "Militar", imp: "Oliva", hint: "Tono" },
        { civ: "Trapecio", imp: "Pirámide", hint: "Figura" },
        { civ: "Anillo", imp: "Aro", hint: "Circular" },
        { civ: "Puente", imp: "Arco", hint: "Construcción" },
        { civ: "Cian", imp: "Magenta", hint: "Imprenta" }
    ],
    "Países y Ciudades": [
        { civ: "España", imp: "Portugal", hint: "Iberia" },
        { civ: "Madrid", imp: "Barcelona", hint: "Capital" },
        { civ: "Francia", imp: "Italia", hint: "Europa" },
        { civ: "Sevilla", imp: "Granada", hint: "Andalucía" },
        { civ: "Londres", imp: "París", hint: "Ciudad" },
        { civ: "Alemania", imp: "Austria", hint: "Idioma" },
        { civ: "Valencia", imp: "Alicante", hint: "Costa" },
        { civ: "Japón", imp: "China", hint: "Asia" },
        { civ: "Nueva York", imp: "Chicago", hint: "EEUU" },
        { civ: "Bilbao", imp: "Vitoria", hint: "Euskadi" },
        { civ: "Marruecos", imp: "Túnez", hint: "África" },
        { civ: "México", imp: "Colombia", hint: "Hispano" },
        { civ: "Zaragoza", imp: "Huesca", hint: "Aragón" },
        { civ: "Málaga", imp: "Marbella", hint: "Sur" },
        { civ: "Roma", imp: "Venecia", hint: "Historia" },
        { civ: "Berlín", imp: "Munich", hint: "Cerveza" },
        { civ: "Vigo", imp: "Coruña", hint: "Galicia" },
        { civ: "Rusia", imp: "Polonia", hint: "Este" },
        { civ: "Australia", imp: "Islandia", hint: "Isla" },
        { civ: "Toledo", imp: "Segovia", hint: "Castilla" },
        { civ: "Tenerife", imp: "Lanzarote", hint: "Canarias" },
        { civ: "Palma", imp: "Ibiza", hint: "Baleares" },
        { civ: "Salamanca", imp: "Valladolid", hint: "León" },
        { civ: "Murcia", imp: "Cartagena", hint: "Levante" },
        { civ: "Brasil", imp: "Argentina", hint: "Fútbol" },
        { civ: "Oviedo", imp: "Gijón", hint: "Asturias" },
        { civ: "Santander", imp: "Laredo", hint: "Cantabria" },
        { civ: "Pamplona", imp: "Logroño", hint: "Norte" },
        { civ: "Lisboa", imp: "Oporto", hint: "Fado" },
        { civ: "Ámsterdam", imp: "Bruselas", hint: "Benelux" },
        { civ: "Tokio", imp: "Kioto", hint: "Oriente" },
        { civ: "Canadá", imp: "Suiza", hint: "Nieve" },
        { civ: "Estambul", imp: "Atenas", hint: "Medio" },
        { civ: "Cádiz", imp: "Huelva", hint: "Carnaval" },
        { civ: "Cáceres", imp: "Badajoz", hint: "Extremadura" }
    ],
    "Emociones y Sentimientos": [
        { civ: "Alegría", imp: "Euforia", hint: "Positivo" },
        { civ: "Tristeza", imp: "Pena", hint: "Llantos" },
        { civ: "Miedo", imp: "Pánico", hint: "Susto" },
        { civ: "Ira", imp: "Rencor", hint: "Enfado" },
        { civ: "Amor", imp: "Cariño", hint: "Afecto" },
        { civ: "Sorpresa", imp: "Alarma", hint: "Inesperado" },
        { civ: "Asco", imp: "Rechazo", hint: "Repugnancia" },
        { civ: "Aburrimiento", imp: "Cansancio", hint: "Tedio" },
        { civ: "Envidia", imp: "Celos", hint: "Deseo" },
        { civ: "Orgullo", imp: "Soberbia", hint: "Ego" },
        { civ: "Culpa", imp: "Pesar", hint: "Moral" },
        { civ: "Vergüenza", imp: "Timidez", hint: "Corte" },
        { civ: "Esperanza", imp: "Ilusión", hint: "Futuro" },
        { civ: "Paz", imp: "Calma", hint: "Relajación" },
        { civ: "Duda", imp: "Confusión", hint: "Mente" },
        { civ: "Gratitud", imp: "Favor", hint: "Gracias" },
        { civ: "Soledad", imp: "Vacío", hint: "Solo" },
        { civ: "Ansiedad", imp: "Estrés", hint: "Nervios" },
        { civ: "Pasión", imp: "Fuego", hint: "Intenso" },
        { civ: "Alivio", imp: "Respiro", hint: "Final" },
        { civ: "Odio", imp: "Ira", hint: "Malicia" },
        { civ: "Fe", imp: "Confianza", hint: "Creer" },
        { civ: "Lástima", imp: "Piedad", hint: "Empatía" },
        { civ: "Interés", imp: "Ganas", hint: "Atención" },
        { civ: "Recuerdo", imp: "Olvido", hint: "Pasado" },
        { civ: "Rabia", imp: "Enfado", hint: "Fuerte" },
        { civ: "Optimismo", imp: "Dicha", hint: "Bien" },
        { civ: "Dolor", imp: "Sufrimiento", hint: "Mal" },
        { civ: "Respeto", imp: "Honor", hint: "Valor" },
        { civ: "Paciencia", imp: "Espera", hint: "Tiempo" },
        { civ: "Motivación", imp: "Impulso", hint: "Energía" },
        { civ: "Humor", imp: "Risa", hint: "Gracia" },
        { civ: "Pena", imp: "Duelo", hint: "Triste" },
        { civ: "Felicidad", imp: "Gozo", hint: "Estado" },
        { civ: "Coraje", imp: "Valor", hint: "Acción" }
    ],
    "Aficiones y Actividades": [
        { civ: "Leer", imp: "Hoja", hint: "Libro" },
        { civ: "Cocinar", imp: "Guisar", hint: "Comida" },
        { civ: "Correr", imp: "Andar", hint: "Piernas" },
        { civ: "Nadar", imp: "Bucear", hint: "Agua" },
        { civ: "Viajar", imp: "Turismo", hint: "Sitios" },
        { civ: "Dibujar", imp: "Pintar", hint: "Arte" },
        { civ: "Cantar", imp: "Gritar", hint: "Voz" },
        { civ: "Bailar", imp: "Saltar", hint: "Cuerpo" },
        { civ: "Gamers", imp: "Consola", hint: "Juego" },
        { civ: "Series", imp: "Pelis", hint: "Pantalla" },
        { civ: "Gimnasio", imp: "Pesas", hint: "Músculo" },
        { civ: "Fotos", imp: "Cámara", hint: "Imagen" },
        { civ: "Plantas", imp: "Huerto", hint: "Tierra" },
        { civ: "Pescar", imp: "Cazar", hint: "Campo" },
        { civ: "Compras", imp: "Rebajas", hint: "Tiendas" },
        { civ: "Concierto", imp: "Ópera", hint: "Música" },
        { civ: "Yoga", imp: "Zen", hint: "Cuerpo" },
        { civ: "Escalar", imp: "Senda", hint: "Monte" },
        { civ: "Skate", imp: "Patín", hint: "Ruedas" },
        { civ: "Bici", imp: "Moto", hint: "Vehículo" },
        { civ: "Cartas", imp: "Damas", hint: "Mesa" },
        { civ: "Piano", imp: "Guitarra", hint: "Instrumento" },
        { civ: "Camping", imp: "Vivac", hint: "Dormir" },
        { civ: "Surf", imp: "Vela", hint: "Olas" },
        { civ: "Puzle", imp: "Maqueta", hint: "Piezas" },
        { civ: "Monedas", imp: "Sellos", hint: "Colección" },
        { civ: "Reparar", imp: "Montar", hint: "Manos" },
        { civ: "Inglés", imp: "Chino", hint: "Hablar" },
        { civ: "Actuar", imp: "Teatro", hint: "Escenario" },
        { civ: "Coser", imp: "Tejer", hint: "Hilo" },
        { civ: "Cine", imp: "Palomitas", hint: "Butaca" },
        { civ: "Pádel", imp: "Tenis", hint: "Deporte" },
        { civ: "Sol", imp: "Playa", hint: "Verano" },
        { civ: "Siesta", imp: "Sueño", hint: "Descanso" },
        { civ: "Tapeo", imp: "Cañas", hint: "Bar" }
    ],
    "Cultura de Internet": [
        { civ: "Meme", imp: "Imagen", hint: "Broma" },
        { civ: "Influencer", imp: "Famoso", hint: "Redes" },
        { civ: "Streamer", imp: "Ibai", hint: "Directo" },
        { civ: "TikTok", imp: "Reels", hint: "Vídeo" },
        { civ: "Viral", imp: "Fama", hint: "Internet" },
        { civ: "Hashtag", imp: "Etiqueta", hint: "Texto" },
        { civ: "Spam", imp: "Basura", hint: "Correo" },
        { civ: "Troll", imp: "Hater", hint: "Usuario" },
        { civ: "Emoji", imp: "Icono", hint: "Móvil" },
        { civ: "Wifi", imp: "Red", hint: "Conexión" },
        { civ: "Google", imp: "Bing", hint: "Web" },
        { civ: "Spoiler", imp: "Final", hint: "Peli" },
        { civ: "Reto", imp: "Challenge", hint: "Prueba" },
        { civ: "Hacker", imp: "Pirata", hint: "Código" },
        { civ: "Blog", imp: "Foro", hint: "Web" },
        { civ: "Clickbait", imp: "Titular", hint: "Noticia" },
        { civ: "Selfie", imp: "Foto", hint: "Cara" },
        { civ: "Drive", imp: "Nube", hint: "Datos" },
        { civ: "Login", imp: "Password", hint: "Entrar" },
        { civ: "Avatar", imp: "Perfil", hint: "Usuario" },
        { civ: "App", imp: "Software", hint: "Descarga" },
        { civ: "Bug", imp: "Fallo", hint: "Error" },
        { civ: "Lag", imp: "Corte", hint: "Red" },
        { civ: "Follow", imp: "Like", hint: "Botón" },
        { civ: "Caché", imp: "Cookies", hint: "Navegador" },
        { civ: "NFT", imp: "Cripto", hint: "Digital" },
        { civ: "Cringe", imp: "Pena", hint: "Sentimiento" },
        { civ: "Dark", imp: "Noche", hint: "Modo" },
        { civ: "Unboxing", imp: "Paquete", hint: "Abrir" },
        { civ: "Webcam", imp: "Micro", hint: "Pc" },
        { civ: "URL", imp: "Link", hint: "Enlace" },
        { civ: "PIN", imp: "Huella", hint: "Seguridad" },
        { civ: "Captura", imp: "Imagen", hint: "Pantalla" },
        { civ: "Email", imp: "Carta", hint: "Mensaje" },
        { civ: "Sticker", imp: "Pegatina", hint: "Whatsapp" }
    ],
    "Cocina y Gastronomía": [
        { civ: "Sartén", imp: "Olla", hint: "Fuego" },
        { civ: "Horno", imp: "Micro", hint: "Calor" },
        { civ: "Chef", imp: "Pinche", hint: "Cocina" },
        { civ: "Sal", imp: "Azúcar", hint: "Polvo" },
        { civ: "Aceite", imp: "Manteca", hint: "Grasa" },
        { civ: "Ajo", imp: "Cebolla", hint: "Bulbo" },
        { civ: "Pelador", imp: "Cuchillo", hint: "Corte" },
        { civ: "Menú", imp: "Carta", hint: "Restaurante" },
        { civ: "Postre", imp: "Dulce", hint: "Final" },
        { civ: "Freír", imp: "Hervir", hint: "Técnica" },
        { civ: "Batidora", imp: "Picadora", hint: "Motor" },
        { civ: "Vino", imp: "Tinto", hint: "Uva" },
        { civ: "Especias", imp: "Hierbas", hint: "Sabor" },
        { civ: "Salsa", imp: "Crema", hint: "Líquido" },
        { civ: "Pasta", imp: "Pizza", hint: "Trigo" },
        { civ: "Carne", imp: "Pollo", hint: "Animal" },
        { civ: "Verdura", imp: "Fruta", hint: "Huerto" },
        { civ: "Tarta", imp: "Pastel", hint: "Dulce" },
        { civ: "Gamba", imp: "Langosta", hint: "Marisco" },
        { civ: "Sopa", imp: "Caldo", hint: "Cuchara" },
        { civ: "Asado", imp: "Plancha", hint: "Cocinado" },
        { civ: "Desayuno", imp: "Cena", hint: "Comida" },
        { civ: "Tapa", imp: "Bocado", hint: "Bar" },
        { civ: "Copa", imp: "Vaso", hint: "Cristal" },
        { civ: "Mantel", imp: "Trapo", hint: "Tela" },
        { civ: "Maitre", imp: "Camarero", hint: "Sala" },
        { civ: "Michelin", imp: "Repsol", hint: "Guía" },
        { civ: "Buffet", imp: "Picoteo", hint: "Libre" },
        { civ: "Crudo", imp: "Hecho", hint: "Punto" },
        { civ: "Picante", imp: "Soso", hint: "Sabor" },
        { civ: "Miel", imp: "Sirop", hint: "Viscoso" },
        { civ: "Nata", imp: "Mousse", hint: "Leche" },
        { civ: "Salado", imp: "Agrio", hint: "Básico" },
        { civ: "Gourmet", imp: "Casero", hint: "Nivel" },
        { civ: "Artesano", imp: "Fabril", hint: "Origen" }
    ],
    "Películas y Series": [
        { civ: "Vader", imp: "Yoda", hint: "Saga" },
        { civ: "Harry", imp: "Hermione", hint: "Magia" },
        { civ: "Berlín", imp: "Tokio", hint: "Atraco" },
        { civ: "Titanic", imp: "Avatar", hint: "Cine" },
        { civ: "Joker", imp: "Batman", hint: "Cómic" },
        { civ: "Marvel", imp: "DC", hint: "Héroes" },
        { civ: "Eleven", imp: "Mike", hint: "Serie" },
        { civ: "Mafia", imp: "Padrino", hint: "Crimen" },
        { civ: "Shrek", imp: "Fiona", hint: "Ogro" },
        { civ: "Trono", imp: "Dragón", hint: "Fantasía" },
        { civ: "Simpson", imp: "Homer", hint: "Amarillo" },
        { civ: "Walter", imp: "Jesse", hint: "Química" },
        { civ: "Bond", imp: "Hunt", hint: "Espía" },
        { civ: "Dino", imp: "Parque", hint: "Animal" },
        { civ: "Miedo", imp: "Susto", hint: "Terror" },
        { civ: "Risa", imp: "Broma", hint: "Comedia" },
        { civ: "Oscar", imp: "Goya", hint: "Premio" },
        { civ: "Actor", imp: "Doble", hint: "Cine" },
        { civ: "Director", imp: "Guion", hint: "Detrás" },
        { civ: "Popcorn", imp: "Nachos", hint: "Comer" },
        { civ: "Netflix", imp: "HBO", hint: "Streaming" },
        { civ: "Zombi", imp: "Vampiro", hint: "Monstruo" },
        { civ: "Pirata", imp: "Corsario", hint: "Mar" },
        { civ: "Gladiador", imp: "César", hint: "Roma" },
        { civ: "Rocky", imp: "Apolo", hint: "Boxeo" },
        { civ: "Stark", imp: "Rogers", hint: "Vengador" },
        { civ: "Sitcom", imp: "Drama", hint: "Género" },
        { civ: "Tráiler", imp: "Teaser", hint: "Avance" },
        { civ: "Doblaje", imp: "Subs", hint: "Idioma" },
        { civ: "CGI", imp: "Efecto", hint: "Imagen" },
        { civ: "Banda", imp: "BSO", hint: "Sonido" },
        { civ: "Sequía", imp: "Duna", hint: "Ciencia" },
        { civ: "Mago", imp: "Bruja", hint: "Varita" },
        { civ: "Ring", imp: "Lucha", hint: "Acción" },
        { civ: "Butaca", imp: "Pantalla", hint: "Lugar" }
    ],
    "Música y Bandas": [
        { civ: "Beatles", imp: "Queen", hint: "Banda" },
        { civ: "Rock", imp: "Pop", hint: "Género" },
        { civ: "Guitarra", imp: "Bajo", hint: "Cuerda" },
        { civ: "Batería", imp: "Caja", hint: "Ritmo" },
        { civ: "Piano", imp: "Órgano", hint: "Teclas" },
        { civ: "Cantar", imp: "Voz", hint: "Boca" },
        { civ: "Festival", imp: "Gira", hint: "Evento" },
        { civ: "Vinilo", imp: "CD", hint: "Físico" },
        { civ: "Spotify", imp: "YouTube", hint: "Red" },
        { civ: "DJ", imp: "Productor", hint: "Mesa" },
        { civ: "Flamenco", imp: "Copla", hint: "Tradición" },
        { civ: "Metal", imp: "Punk", hint: "Fuerte" },
        { civ: "Jazz", imp: "Blues", hint: "Clásico" },
        { civ: "Rap", imp: "HipHop", hint: "Urbano" },
        { civ: "Coro", imp: "Ópera", hint: "Canto" },
        { civ: "Micro", imp: "Amplificador", hint: "Equipo" },
        { civ: "Letra", imp: "Rima", hint: "Texto" },
        { civ: "Álbum", imp: "Disco", hint: "Obra" },
        { civ: "Grammy", imp: "Premio", hint: "Gala" },
        { civ: "Aitana", imp: "Lola", hint: "Española" },
        { civ: "Rosalía", imp: "Quevedo", hint: "Top" },
        { civ: "Violín", imp: "Arco", hint: "Cuerda" },
        { civ: "Flauta", imp: "Pito", hint: "Viento" },
        { civ: "Fan", imp: "Ídolo", hint: "Persona" },
        { civ: "Baile", imp: "Danza", hint: "Cuerpo" },
        { civ: "Estudio", imp: "Ensayo", hint: "Lugar" },
        { civ: "Solo", imp: "Dúo", hint: "Grupo" },
        { civ: "Agudo", imp: "Grave", hint: "Tono" },
        { civ: "Melodía", imp: "Acorde", hint: "Sonido" },
        { civ: "Rapero", imp: "Trapero", hint: "Cantante" },
        { civ: "Sinfonía", imp: "Sonata", hint: "Clásica" },
        { civ: "Techno", imp: "House", hint: "Baile" },
        { civ: "Grito", imp: "Susurro", hint: "Voz" },
        { civ: "Altavoz", imp: "Cascos", hint: "Escuchar" },
        { civ: "Estribillo", imp: "Verso", hint: "Canción" }
    ],
    "Profesiones": [
        { civ: "Médico", imp: "Enfermera", hint: "Salud" },
        { civ: "Docente", imp: "Mentor", hint: "Escuela" },
        { civ: "Guardia", imp: "Policía", hint: "Seguridad" },
        { civ: "Bombero", imp: "Casco", hint: "Fuego" },
        { civ: "Chef", imp: "Mesero", hint: "Comer" },
        { civ: "Obrero", imp: "Arquitecto", hint: "Obra" },
        { civ: "Juez", imp: "Fiscal", hint: "Ley" },
        { civ: "Fontanero", imp: "Tubo", hint: "Casa" },
        { civ: "Mecánico", imp: "Motor", hint: "Taller" },
        { civ: "Peluquero", imp: "Tijera", hint: "Pelo" },
        { civ: "Prensa", imp: "Radio", hint: "Noticia" },
        { civ: "Piloto", imp: "Barco", hint: "Viaje" },
        { civ: "Taxista", imp: "Bus", hint: "Ciudad" },
        { civ: "Cajero", imp: "Venta", hint: "Tienda" },
        { civ: "Actor", imp: "Teatro", hint: "Cine" },
        { civ: "Soldado", imp: "Fusil", hint: "Guerra" },
        { civ: "Físico", imp: "Químico", hint: "Ciencia" },
        { civ: "Pc", imp: "Web", hint: "Sistemas" },
        { civ: "Campesino", imp: "Vaca", hint: "Campo" },
        { civ: "Escritor", imp: "Libro", hint: "Letras" },
        { civ: "Dibujante", imp: "Diseño", hint: "Imagen" },
        { civ: "Atleta", imp: "Deporte", hint: "Meta" },
        { civ: "Perro", imp: "Clínica", hint: "Animales" },
        { civ: "Psicólogo", imp: "Mente", hint: "Terapia" },
        { civ: "Espacio", imp: "Luna", hint: "Cielo" },
        { civ: "Pan", imp: "Horno", hint: "Masa" },
        { civ: "Pintor", imp: "Pared", hint: "Casa" },
        { civ: "Jardín", imp: "Planta", hint: "Poda" },
        { civ: "Diputado", imp: "Alcalde", hint: "Voto" },
        { civ: "Banca", imp: "Bolsa", hint: "Euros" },
        { civ: "Circo", imp: "Mago", hint: "Niños" },
        { civ: "Moda", imp: "Pasarela", hint: "Ropa" },
        { civ: "Turista", imp: "Hotel", hint: "Guía" },
        { civ: "Fósil", imp: "Pasado", hint: "Tierra" },
        { civ: "Trompeta", imp: "Voz", hint: "Música" }
    ],
    "Escuela y Educación": [
        { civ: "Examen", imp: "Nota", hint: "Estudio" },
        { civ: "Tarea", imp: "Libro", hint: "Casa" },
        { civ: "Patio", imp: "Juego", hint: "Descanso" },
        { civ: "Mochila", imp: "Libreta", hint: "Escuela" },
        { civ: "Bolígrafo", imp: "Lápiz", hint: "Tinta" },
        { civ: "Goma", imp: "Papel", hint: "Borrar" },
        { civ: "Pizarra", imp: "Tiza", hint: "Clase" },
        { civ: "Director", imp: "Profe", hint: "Cole" },
        { civ: "Alumno", imp: "Clase", hint: "Niño" },
        { civ: "Lección", imp: "Tema", hint: "Saber" },
        { civ: "Sumas", imp: "Letras", hint: "Materia" },
        { civ: "Guerra", imp: "Mapa", hint: "Letras" },
        { civ: "Átomo", imp: "Cuerpo", hint: "Ciencia" },
        { civ: "Inglés", imp: "Verbo", hint: "Hablar" },
        { civ: "Gimnasio", imp: "Pelota", hint: "Cuerpo" },
        { civ: "Suspenso", imp: "Aprobar", hint: "Nota" },
        { civ: "Uni", imp: "Insti", hint: "Centro" },
        { civ: "Pupitre", imp: "Silla", hint: "Mueble" },
        { civ: "Regla", imp: "Escuadra", hint: "Medir" },
        { civ: "Danza", imp: "Coro", hint: "Taller" },
        { civ: "Beca", imp: "Dinero", hint: "Ayuda" },
        { civ: "Tesis", imp: "Grado", hint: "Final" },
        { civ: "Fuera", imp: "Viaje", hint: "Salida" },
        { civ: "Típex", imp: "Boli", hint: "Error" },
        { civ: "Carpeta", imp: "Folio", hint: "Papel" },
        { civ: "Cuentas", imp: "Números", hint: "Cálculo" },
        { civ: "Aula", imp: "Laboratorio", hint: "SitiO" },
        { civ: "Protesta", imp: "Paro", hint: "Huelga" },
        { civ: "Faltas", imp: "Aviso", hint: "Castigo" },
        { civ: "Globo", imp: "Mapa", hint: "Mundo" },
        { civ: "Pincel", imp: "Témpera", hint: "Plástica" },
        { civ: "Agenda", imp: "Móvil", hint: "Notas" },
        { civ: "Flauta", imp: "Pentagrama", hint: "Solfa" },
        { civ: "Comedor", imp: "Bandeja", hint: "Comer" },
        { civ: "Becario", imp: "Prácticas", hint: "Trabajo" }
    ],
    "Ciencia y Tecnología": [
        { civ: "Red", imp: "Wifi", hint: "Internet" },
        { civ: "Pc", imp: "Ratón", hint: "Pc" },
        { civ: "Móvil", imp: "Micro", hint: "Chip" },
        { civ: "Robot", imp: "Cable", hint: "Hierro" },
        { civ: "Marte", imp: "Sol", hint: "Cielo" },
        { civ: "Gen", imp: "Virus", hint: "Vida" },
        { civ: "Átomo", imp: "Luz", hint: "Física" },
        { civ: "Bata", imp: "Tubo", hint: "Ciencia" },
        { civ: "NASA", imp: "ESA", hint: "Espacio" },
        { civ: "Software", imp: "Web", hint: "Código" },
        { civ: "Telescopio", imp: "Lupa", hint: "Lente" },
        { civ: "Sonda", imp: "Cohete", hint: "Vuelo" },
        { civ: "Luz", imp: "Pila", hint: "Voltio" },
        { civ: "Rayo", imp: "Láser", hint: "Haz" },
        { civ: "Placa", imp: "Panel", hint: "Sol" },
        { civ: "Cero", imp: "Uno", hint: "Binario" },
        { civ: "Vibración", imp: "Onda", hint: "Sonido" },
        { civ: "Química", imp: "Mezcla", hint: "Laboratorio" },
        { civ: "Cura", imp: "Dosis", hint: "Vacuna" },
        { civ: "Mono", imp: "Fósil", hint: "Origen" },
        { civ: "Dron", imp: "Hélice", hint: "Volar" },
        { civ: "IA", imp: "Bot", hint: "Cerebro" },
        { civ: "Dato", imp: "Bit", hint: "Pc" },
        { civ: "Led", imp: "Monitor", hint: "Imagen" },
        { civ: "Teclas", imp: "Clic", hint: "Control" },
        { civ: "Tinta", imp: "Papel", hint: "Impresora" },
        { civ: "Muela", imp: "Implante", hint: "Biónico" },
        { civ: "Gafas", imp: "Casco", hint: "Virtual" },
        { civ: "Bio", imp: "Nano", hint: "Futuro" },
        { civ: "Cable", imp: "Luz", hint: "Fibra" },
        { civ: "Apps", imp: "Play", hint: "Tienda" },
        { civ: "Apple", imp: "Java", hint: "Sistemas" },
        { civ: "Nube", imp: "Disco", hint: "Memoria" },
        { civ: "Hack", imp: "Virus", hint: "Ataque" },
        { civ: "Satélite", imp: "Antena", hint: "Onda" }
    ],
    "Deportes": [
        { civ: "Fútbol", imp: "Gol", hint: "Césped" },
        { civ: "Basket", imp: "Aro", hint: "Cancha" },
        { civ: "Tenis", imp: "Red", hint: "Raqueta" },
        { civ: "Bici", imp: "Rueda", hint: "Ruta" },
        { civ: "Coche", imp: "F1", hint: "Circuito" },
        { civ: "Mar", imp: "Cloro", hint: "Nadar" },
        { civ: "Salto", imp: "Valla", hint: "Correr" },
        { civ: "Ring", imp: "Guante", hint: "Puño" },
        { civ: "Hoyo", imp: "Palo", hint: "Golf" },
        { civ: "Nieve", imp: "Esquí", hint: "Frío" },
        { civ: "Tabla", imp: "Olas", hint: "Surf" },
        { civ: "Malla", imp: "Estera", hint: "Cuerpo" },
        { civ: "Red", imp: "Arena", hint: "Vóley" },
        { civ: "Melé", imp: "Placaje", hint: "Rugby" },
        { civ: "Jaque", imp: "Ficha", hint: "Tablero" },
        { civ: "Mesa", imp: "Pala", hint: "Pingpong" },
        { civ: "Arnés", imp: "Roca", hint: "Escalada" },
        { civ: "Puck", imp: "Stick", hint: "Hockey" },
        { civ: "Piragua", imp: "Remo", hint: "Agua" },
        { civ: "Diana", imp: "Arco", hint: "Flecha" },
        { civ: "Taco", imp: "Bola", hint: "Billar" },
        { civ: "Silla", imp: "Casco", hint: "Caballo" },
        { civ: "Cinto", imp: "Tatami", hint: "Lucha" },
        { civ: "Músculo", imp: "Pesas", hint: "Fuerza" },
        { civ: "Coreo", imp: "Ritmo", hint: "Gimnasia" },
        { civ: "Meta", imp: "Podio", hint: "Carrera" },
        { civ: "Pelota", imp: "Balón", hint: "Esfera" },
        { civ: "Grada", imp: "Cancha", hint: "Lugar" },
        { civ: "Silbato", imp: "Falta", hint: "Árbitro" },
        { civ: "Oro", imp: "Copa", hint: "Triunfo" },
        { civ: "Antorcha", imp: "Aros", hint: "Olimpiada" },
        { civ: "Pala", imp: "Raqueta", hint: "Mango" },
        { civ: "Malla", imp: "Casco", hint: "Protección" },
        { civ: "Viento", imp: "Vela", hint: "Náutica" },
        { civ: "Sudor", imp: "Ducha", hint: "Ejercicio" }
    ],
    "Superhéroes": [
        { civ: "Batman", imp: "Robin", hint: "Capa" },
        { civ: "Superman", imp: "Volar", hint: "Héroe" },
        { civ: "Araña", imp: "Rojo", hint: "Muro" },
        { civ: "Hierro", imp: "Robot", hint: "Metal" },
        { civ: "Verde", imp: "Furia", hint: "Fuerza" },
        { civ: "Trueno", imp: "Dios", hint: "Martillo" },
        { civ: "Mujer", imp: "Lazo", hint: "Escudo" },
        { civ: "Correr", imp: "Veloz", hint: "Rayo" },
        { civ: "Garras", imp: "Lobo", hint: "Acero" },
        { civ: "Escudo", imp: "Bandera", hint: "Capitán" },
        { civ: "Arco", imp: "Viuda", hint: "Equipo" },
        { civ: "Magia", imp: "Capa", hint: "Doctor" },
        { civ: "Pez", imp: "Agua", hint: "Tridente" },
        { civ: "Pantera", imp: "Gato", hint: "Selva" },
        { civ: "Grupo", imp: "Mutante", hint: "Poder" },
        { civ: "Ciego", imp: "Rojo", hint: "Justicia" },
        { civ: "Anillo", imp: "Verde", hint: "Luz" },
        { civ: "Máscara", imp: "Capa", hint: "Disfraz" },
        { civ: "Villano", imp: "Malo", hint: "Enemigo" },
        { civ: "Ciudad", imp: "Pueblo", hint: "Defensa" },
        { civ: "Chiste", imp: "Risa", hint: "Guasón" },
        { civ: "Gema", imp: "Guante", hint: "Poder" },
        { civ: "Piedra", imp: "Roca", hint: "Metal" },
        { civ: "Disfraz", imp: "Malla", hint: "Traje" },
        { civ: "Viñeta", imp: "Papel", hint: "Cómic" },
        { civ: "Mundo", imp: "Tierra", hint: "Salvar" },
        { civ: "Oculto", imp: "Secreto", hint: "Doble" },
        { civ: "Coche", imp: "Nave", hint: "Viaje" },
        { civ: "Rayo", imp: "Vuelo", hint: "Shazam" },
        { civ: "Infierno", imp: "Cielo", hint: "Demonio" },
        { civ: "Gata", imp: "Látigo", hint: "Ladrón" },
        { civ: "Mapache", imp: "Árbol", hint: "Galaxia" },
        { civ: "Imán", imp: "Metal", hint: "Magneto" },
        { civ: "Casco", imp: "Vuelo", hint: "Iron" },
        { civ: "Héroe", imp: "Capitán", hint: "Líder" }
    ],
    "Transporte": [
        { civ: "Coche", imp: "Bus", hint: "Ruedas" },
        { civ: "Moto", imp: "Bici", hint: "Manillar" },
        { civ: "Tren", imp: "Vía", hint: "Raíl" },
        { civ: "Avión", imp: "Vuelo", hint: "Aire" },
        { civ: "Barco", imp: "Vela", hint: "Agua" },
        { civ: "AVE", imp: "Metro", hint: "Tren" },
        { civ: "Uber", imp: "Taxi", hint: "App" },
        { civ: "Patín", imp: "Skate", hint: "Ciudad" },
        { civ: "Grúa", imp: "Trailer", hint: "Camión" },
        { civ: "Helicóptero", imp: "Ala", hint: "Hélice" },
        { civ: "Yate", imp: "Canoa", hint: "Ocio" },
        { civ: "Globo", imp: "Cesta", hint: "Gas" },
        { civ: "Ambulancia", imp: "Sirena", hint: "Urgencia" },
        { civ: "Fúnebre", imp: "Negro", hint: "Caja" },
        { civ: "Tractor", imp: "Arado", hint: "Campo" },
        { civ: "Parada", imp: "Andén", hint: "Espera" },
        { civ: "Puerto", imp: "Aduana", hint: "Viaje" },
        { civ: "Billete", imp: "Abono", hint: "Ticket" },
        { civ: "Súper", imp: "Gasoil", hint: "Motor" },
        { civ: "Freno", imp: "Embrague", hint: "Pedal" },
        { civ: "Volante", imp: "Pomo", hint: "Mano" },
        { civ: "Atasco", imp: "Cola", hint: "Calle" },
        { civ: "Chofer", imp: "Piloto", hint: "Manejar" },
        { civ: "Polizón", imp: "Maleta", hint: "Viajero" },
        { civ: "Multa", imp: "Radar", hint: "Control" },
        { civ: "Luz", imp: "Señal", hint: "Tráfico" },
        { civ: "Vía", imp: "Acera", hint: "Suelo" },
        { civ: "Muro", imp: "Valla", hint: "Separador" },
        { civ: "Paso", imp: "Cruce", hint: "Cebra" },
        { civ: "Túnel", imp: "Puente", hint: "Paso" },
        { civ: "Escala", imp: "Maleta", hint: "Vuelo" },
        { civ: "Ancla", imp: "Muelle", hint: "Barco" },
        { civ: "Gas", imp: "Freno", hint: "Velocidad" },
        { civ: "Airbag", imp: "Cinto", hint: "Choque" },
        { civ: "Mapa", imp: "GPS", hint: "Guía" }
    ],
    "Videojuegos": [
        { civ: "Mario", imp: "Luigi", hint: "Salto" },
        { civ: "Zelda", imp: "Link", hint: "Hada" },
        { civ: "Pika", imp: "Ash", hint: "Bola" },
        { civ: "Minecraft", imp: "Cubo", hint: "Pico" },
        { civ: "Fortnite", imp: "Baile", hint: "Pavo" },
        { civ: "FIFA", imp: "Pelota", hint: "Fútbol" },
        { civ: "Mando", imp: "Tecla", hint: "Jugar" },
        { civ: "Skin", imp: "Disfraz", hint: "Pago" },
        { civ: "Xbox", imp: "Play", hint: "Tv" },
        { civ: "Game", imp: "Over", hint: "Final" },
        { civ: "Nivel", imp: "Misión", hint: "Punto" },
        { civ: "Jefe", imp: "Malo", hint: "Final" },
        { civ: "Botón", imp: "Stick", hint: "Mano" },
        { civ: "Pc", imp: "Monitor", hint: "Teclado" },
        { civ: "Tetris", imp: "Línea", hint: "Pieza" },
        { civ: "Sonic", imp: "Azul", hint: "Anillo" },
        { civ: "Halo", imp: "Soldado", hint: "Casco" },
        { civ: "Arcade", imp: "Salón", hint: "Ficha" },
        { civ: "Gamer", imp: "Pro", hint: "Persona" },
        { civ: "Lag", imp: "Ping", hint: "Red" },
        { civ: "Steam", imp: "Epic", hint: "Tienda" },
        { civ: "Retro", imp: "Viejo", hint: "Pixel" },
        { civ: "Sims", imp: "Casa", hint: "Vida" },
        { civ: "Roblox", imp: "Bloque", hint: "Online" },
        { civ: "Craft", imp: "Mina", hint: "Pico" },
        { civ: "Wii", imp: "Switch", hint: "Mando" },
        { civ: "Vida", imp: "Corazón", hint: "Barra" },
        { civ: "Susto", imp: "Miedo", hint: "Terror" },
        { civ: "Mundo", imp: "Mapa", hint: "Abierto" },
        { civ: "Speed", imp: "Rápido", hint: "Carrera" },
        { civ: "Combo", imp: "Golpe", hint: "Lucha" },
        { civ: "Mana", imp: "Hechizo", hint: "Magia" },
        { civ: "Skin", imp: "Mod", hint: "Cambio" },
        { civ: "Noob", imp: "Manco", hint: "Novato" },
        { civ: "Quest", imp: "Exp", hint: "Rol" }
    ],
    "Clima y Naturaleza": [
        { civ: "Lluvia", imp: "Agua", hint: "Cielo" },
        { civ: "Nieve", imp: "Frío", hint: "Blanco" },
        { civ: "Sol", imp: "Luz", hint: "Calor" },
        { civ: "Nube", imp: "Gris", hint: "Viento" },
        { civ: "Trueno", imp: "Rayo", hint: "RUIDO" },
        { civ: "Monte", imp: "Pico", hint: "Roca" },
        { civ: "Río", imp: "Mar", hint: "Agua" },
        { civ: "Bosque", imp: "Pino", hint: "Árbol" },
        { civ: "Selva", imp: "Liana", hint: "Verde" },
        { civ: "Arena", imp: "Duna", hint: "Seco" },
        { civ: "Flor", imp: "Hoja", hint: "Planta" },
        { civ: "Fuego", imp: "Lava", hint: "Quemar" },
        { civ: "Hielo", imp: "Polo", hint: "Glace" },
        { civ: "Isla", imp: "Playa", hint: "Mar" },
        { civ: "Cueva", imp: "Oso", hint: "Suelo" },
        { civ: "Viento", imp: "Aire", hint: "Soplo" },
        { civ: "Niebla", imp: "Nube", hint: "Gris" },
        { civ: "Otoño", imp: "Hoja", hint: "Tiempo" },
        { civ: "Verano", imp: "Calor", hint: "Sol" },
        { civ: "Hierba", imp: "Prado", hint: "Verde" },
        { civ: "Plástico", imp: "Humo", hint: "Basura" },
        { civ: "Tierra", imp: "Barro", hint: "Lodo" },
        { civ: "Animal", imp: "Bicho", hint: "Ser" },
        { civ: "Piedra", imp: "Guijarro", hint: "Duro" },
        { civ: "Arco", imp: "Iris", hint: "Cielo" },
        { civ: "Luna", imp: "Noche", hint: "Luz" },
        { civ: "Día", imp: "Noche", hint: "Tiempo" },
        { civ: "Ola", imp: "Surf", hint: "Agua" },
        { civ: "Rayo", imp: "Chispa", hint: "Luz" },
        { civ: "Clima", imp: "Mapa", hint: "Tiempo" },
        { civ: "Ecología", imp: "Bio", hint: "Mundo" },
        { civ: "Volcán", imp: "Fuego", hint: "Monte" },
        { civ: "Humedad", imp: "Agua", hint: "Mojado" },
        { civ: "Huracán", imp: "Giro", hint: "Viento" },
        { civ: "Tornado", imp: "Embudo", hint: "Aire" }
    ]
};